// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTeeTimes(arg1, arg2) {
  return window['go']['main']['App']['GetTeeTimes'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ParseEnvFile(arg1, arg2) {
  return window['go']['main']['App']['ParseEnvFile'](arg1, arg2);
}
