// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function GetTeeTimes(arg1:Array<string>,arg2:time.Time):Promise<main.TeeTime>;

export function Greet(arg1:string):Promise<string>;

export function ParseEnvFile(arg1:string,arg2:string):Promise<main.Login>;
